<template>
  <div>
    <!-- 
      By default this is 20px. We want to make the timeline come close to the edge to save space
    hence made it 3px
    This controls the space between edge of the card and the line that shows the dots
    -->
    <el-card class="box-card" :body-style="{ paddingLeft: '3px' }">
      <div slot="header" class="clearfix">
        <span :tabindex="cfPosInArCards * 100 + 1">Reminders</span>
        <el-button-group style="float: right;">
          <el-button style="padding: 3px;" type="success" plain tabindex="-1" @click="mfOpenACtInCl"
            >A</el-button
          >
          <el-button style="padding: 3px;" type="primary" plain tabindex="-1" @click="mfOpenMCtInCl"
            >M</el-button
          >
          <el-button style="padding: 3px;" type="warning" plain tabindex="-1">D</el-button>
          <el-button style="padding: 3px;" type="info" plain tabindex="-1" @click="mfOpenXCtInCl"
            >X</el-button
          >
        </el-button-group>
      </div>
      <!-- explanation of following params:
            1. padding-inline-start: 20px
              This is the space between edge of the card and the line that shows the dots
              By default this is 40px 
            2. $id   
              This is incremental number generated by vuex-orm 
        -->
      <el-timeline style="padding-inline-start: 20px;">
        <el-timeline-item
          v-for="row in cfArOfRemForDisplayInTable"
          :key="row.$id"
          :timestamp="row.createdAt"
          :type="row.type"
          :tabindex="cfPosInArCards * 100 + 2"
        >
          {{ row.remDesc }}
          <el-button-group style="float: right;">
            <el-button type="primary" size="mini" style="padding: 3px;" plain tabindex="-1"
              >C</el-button
            >
            <el-button type="warning" size="mini" style="padding: 3px;" plain tabindex="-1"
              >D</el-button
            >
          </el-button-group>
        </el-timeline-item>
      </el-timeline>
    </el-card>
  </div>
</template>

<script>
import ormRem from '@/cts/spi/rem/db/vuex-orm/rem.js'

export default {
  data() {
    return {}
  },
  computed: {
    cfPosInArCards() {
      const arCards = this.$store.state.vstObjCardsInCSOfVL.arCards
      console.log(arCards)
      const obj = arCards.find((x) => x.label === 'reminders')
      const idx = arCards.indexOf(obj)
      console.log(idx)
      return idx
    },
    cfArOfRemForDisplayInTable() {
      const arFromORM = ormRem.getValidUniqueUuidNotEmptyRows('remDesc')

      /*  Q) Should this function return the array it gets from ORM or modify the array?
              Option1: Return ORM array
                  -ves:
                    1. Created at needs to be made inside the template
                    2. Empty row needs to be filtered out in template
                  +ves:
                    No need to run the for loop
      */

      const arRemsForDisplay = []
      let obj = {}
      if (arFromORM.length) {
        let date = ''
        for (let i = 0; i < arFromORM.length; i++) {
          obj = {}
          obj.remDesc = arFromORM[i].remDesc
          // For date format ref: /cts/spi/rem/vl/timeline.vue:53
          date = new Date(arFromORM[i].ROW_START)
          obj.createdAt = date.toLocaleString('default', { month: 'long' }) + '-' + date.getDate()
          obj.rowStateInThisSession = arFromORM[i].rowStateInThisSession
          obj.uuid = arFromORM[i].uuid
          obj.$id = arFromORM[i].$id
          obj.id = arFromORM[i].id
          arRemsForDisplay.push(obj)
        }
      }
      return arRemsForDisplay
    },
  },
  mounted() {},
  methods: {
    mfOpenACtInCl() {
      this.$store.commit('mtfShowNewFirstTabInClFromSearchPhrase', {
        searchTerm: 'add reminder',
      })
    },
    mfOpenMCtInCl() {
      this.$store.commit('mtfShowNewFirstTabInClFromSearchPhrase', {
        searchTerm: 'multi change reminder',
      })
    },
    mfOpenXCtInCl() {
      this.$store.commit('mtfShowNewFirstTabInClFromSearchPhrase', {
        searchTerm: 'discontinued reminders',
      })
    },
  },
}
</script>
