<template>
  <div>
    <!-- 
      By default this is 20px. We want to make the timeline come close to the edge to save space
    hence made it 3px
    This controls the space between edge of the card and the line that shows the dots
    -->
    <el-card class="box-card" :body-style="{ paddingLeft: '3px' }">
      <div slot="header" class="clearfix">
        <span>Reminders</span>
        <el-button-group style="float: right;">
          <el-button style="padding: 3px;" type="success" plain @click="mfOpenADialog">A</el-button>
          <el-button style="padding: 3px;" type="primary" plain @click="mfOpenMDialog">M</el-button>
          <el-button style="padding: 3px;" type="warning" plain>D</el-button>
          <el-button style="padding: 3px;" type="info" plain @click="mfOpenXDialog">X</el-button>
        </el-button-group>
      </div>
      <!-- explanation of following params:
            1. padding-inline-start: 20px
              This is the space between edge of the card and the line that shows the dots
              By default this is 40px 
            2. $id   
              This is incremental number generated by vuex-orm 
        -->
      <el-timeline style="padding-inline-start: 20px;">
        <el-timeline-item
          v-for="row in dataTable"
          :key="row.$id"
          :timestamp="row.createdAt"
          :type="row.type"
        >
          {{ row.remDesc }}
          <el-button-group style="float: right;">
            <el-button type="primary" size="mini" style="padding: 3px;" plain>C</el-button>
            <el-button type="warning" size="mini" style="padding: 3px;" plain>D</el-button>
          </el-button-group>
        </el-timeline-item>
      </el-timeline>
    </el-card>
  </div>
</template>

<script>
import ormSearchPhraseUiToCT from '@/cts/core/vl-search-box/vuex-orm/searchUIToCT'
import ormRem from '@/cts/spi/rem/db/vuex-orm/rem.js'

export default {
  data() {
    return {
      // dataTable: [],
    }
  },
  computed: {
    dataTable() {
      const dataTable = []
      const arFromORM = ormRem.query().get()
      if (arFromORM.length) {
        let obj = []
        let date = ''
        console.log('unsaved data found', arFromORM, arFromORM[0].uuid)
        for (let i = 0; i < arFromORM.length; i++) {
          obj = {}
          obj.remDesc = arFromORM[i].remDesc
          /*
          To get the number of the month:
          obj.createdAt = date.getMonth() + 1 + "-" + date.getDate()

          To get the name of the month:
          Ref: https://stackoverflow.com/questions/1643320/get-month-name-from-date
          */
          date = new Date(arFromORM[i].ROW_START)
          obj.createdAt = date.toLocaleString('default', { month: 'long' }) + '-' + date.getDate()
          if (arFromORM[i].$isDirty) {
            obj.type = 'warning'
          } else {
            obj.type = ''
          }

          dataTable.push(obj)
        }
      }
      console.log(dataTable)
      return dataTable
    },
  },
  mounted() {},
  methods: {
    mfOpenADialog() {
      console.log('show add dialog')
      const arFromORM = ormSearchPhraseUiToCT.query().search('add reminder').get()
      const objRowFromORM = arFromORM[0]
      console.log(objRowFromORM)
      const tab = {
        label: objRowFromORM.value,
        ctToShow: require('@/cts/' + objRowFromORM.ctToShowInCL).default,
        ctAbbr: objRowFromORM.ctAbbr,
        id: objRowFromORM.id,
        closable: true,
      }
      this.$store.commit('mtfShowNewFirstTabInCl', tab)
    },
    mfOpenMDialog() {
      console.log('show add dialog')
      const arFromORM = ormSearchPhraseUiToCT.query().search('multi change reminder').get()
      const objRowFromORM = arFromORM[0]
      console.log(objRowFromORM)
      const tab = {
        label: objRowFromORM.value,
        ctToShow: require('@/cts/' + objRowFromORM.ctToShowInCL).default,
        ctAbbr: objRowFromORM.ctAbbr,
        id: objRowFromORM.id,
        closable: true,
      }
      this.$store.commit('mtfShowNewFirstTabInCl', tab)
    },
    mfOpenXDialog() {
      console.log('show add dialog')
      const arFromORM = ormSearchPhraseUiToCT.query().search('discontinued reminders').get()
      const objRowFromORM = arFromORM[0]
      console.log(objRowFromORM)
      const tab = {
        label: objRowFromORM.value,
        ctToShow: require('@/cts/' + objRowFromORM.ctToShowInCL).default,
        ctAbbr: objRowFromORM.ctAbbr,
        id: objRowFromORM.id,
        closable: true,
      }
      this.$store.commit('mtfShowNewFirstTabInCl', tab)
    },
  },
}
</script>
